export const restaurantDummyData = [
  {
    id: 1,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 2,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 3,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 4,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 5,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 6,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 7,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 8,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 9,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "open",
    imageUrl: "/image.jpg",
  },
  {
    id: 10,
    name: "Olive Chicken",
    rating: 5,
    type: "THAI",
    priceRange: 2,
    status: "closed",
    imageUrl: "/image.jpg",
  },
];
